# Generated by Django 4.1.11 on 2023-09-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycollection',
            name='name',
            field=models.CharField(max_length=90),
        ),
    ]
