# Generated by Django 4.1.11 on 2023-09-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('NIC', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=15)),
                ('wardID', models.IntegerField()),
                ('mobileNumber', models.IntegerField()),
            ],
        ),
    ]
